### PR TITLE
add support for vert and Vert delimiters

### PR DESCRIPTION
**Pull request by dankessler**
useful for typing norms, absolute values, etc

I tried to follow the convention where lower case corresponds to \left \right
balanced and upper case is not, so I had to come up with a different letter for
Vert (double pipe). I went with "n" for norm, since, at least in my discipline,
||x|| is typically used to denote a norm

I've made changes for delimiter insertion (in evil-tex-delim-map),
delimiter selection (in evil-tex--select-delim which other functions rely on for
delimiter logic), and in the documentation

### CODE REVIEW

**Comment by ymarco** [comment]
Pushed in 6e461c1. Thanks for everything!

**Comment by dankessler** [comment]
Happy to contribute. Thanks for such an amazingly useful package and for being so responsive to PR's. 

PS: I infer that evil-tex is already included in doom, but I'm working on adding it to [spacemacs here](https://github.com/syl20bnr/spacemacs/pull/15471)

**Comment by ymarco** [comment]
Haha. I agree, the toggles are quite magnificent.

**Comment by dankessler** [comment]
:) 

I really enjoyed the [subtle humor in the `evil-tex` documentation](https://github.com/iyefrat/evil-tex/blob/master/README.org#user-options) and did my best to [mirror it wherever I could](https://github.com/syl20bnr/spacemacs/pull/15471/files#diff-cdcc70e0d738cd538721bdb29266e3e0e7fabf7fc1f193cbd7957ced59a46648R342-R345).

**Pull request closed without merging**
